use crate::instructions::*;
use crate::registers::Reg8;

pub static OPCODES: [&(dyn Instruction + Sync); 0x100] = [
    /* 0x00 */ &NOP,
    /* 0x01 */ &NOP,
    /* 0x02 */ &NOP,
    /* 0x03 */ &NOP,
    /* 0x04 */ &NOP,
    /* 0x05 */ &NOP,
    /* 0x06 */ &NOP,
    /* 0x07 */ &NOP,
    /* 0x08 */ &NOP,
    /* 0x09 */ &NOP,
    /* 0x0a */ &NOP,
    /* 0x0b */ &NOP,
    /* 0x0c */ &NOP,
    /* 0x0d */ &NOP,
    /* 0x0e */ &NOP,
    /* 0x0f */ &NOP,
    /* 0x10 */ &NOP,
    /* 0x11 */ &NOP,
    /* 0x12 */ &NOP,
    /* 0x13 */ &NOP,
    /* 0x14 */ &NOP,
    /* 0x15 */ &NOP,
    /* 0x16 */ &NOP,
    /* 0x17 */ &NOP,
    /* 0x18 */ &JumpRelative { condition: None },
    /* 0x19 */ &NOP,
    /* 0x1a */ &NOP,
    /* 0x1b */ &NOP,
    /* 0x1c */ &NOP,
    /* 0x1d */ &NOP,
    /* 0x1e */ &NOP,
    /* 0x1f */ &NOP,
    /* 0x20 */ &JumpRelative {
        condition: Some(Condition::NZ),
    },
    /* 0x21 */ &NOP,
    /* 0x22 */ &NOP,
    /* 0x23 */ &NOP,
    /* 0x24 */ &NOP,
    /* 0x25 */ &NOP,
    /* 0x26 */ &NOP,
    /* 0x27 */ &NOP,
    /* 0x28 */ &JumpRelative {
        condition: Some(Condition::Z),
    },
    /* 0x29 */ &NOP,
    /* 0x2a */ &NOP,
    /* 0x2b */ &NOP,
    /* 0x2c */ &NOP,
    /* 0x2d */ &NOP,
    /* 0x2e */ &NOP,
    /* 0x2f */ &NOP,
    /* 0x30 */ &JumpRelative {
        condition: Some(Condition::NC),
    },
    /* 0x31 */ &NOP,
    /* 0x32 */ &NOP,
    /* 0x33 */ &NOP,
    /* 0x34 */ &NOP,
    /* 0x35 */ &NOP,
    /* 0x36 */ &NOP,
    /* 0x37 */ &NOP,
    /* 0x38 */ &JumpRelative {
        condition: Some(Condition::C),
    },
    /* 0x39 */ &NOP,
    /* 0x3a */ &NOP,
    /* 0x3b */ &NOP,
    /* 0x3c */ &NOP,
    /* 0x3d */ &NOP,
    /* 0x3e */ &NOP,
    /* 0x3f */ &NOP,
    /* 0x40 */ &NOP,
    /* 0x41 */ &NOP,
    /* 0x42 */ &NOP,
    /* 0x43 */ &NOP,
    /* 0x44 */ &NOP,
    /* 0x45 */ &NOP,
    /* 0x46 */ &NOP,
    /* 0x47 */ &NOP,
    /* 0x48 */ &NOP,
    /* 0x49 */ &NOP,
    /* 0x4a */ &NOP,
    /* 0x4b */ &NOP,
    /* 0x4c */ &NOP,
    /* 0x4d */ &NOP,
    /* 0x4e */ &NOP,
    /* 0x4f */ &NOP,
    /* 0x50 */ &NOP,
    /* 0x51 */ &NOP,
    /* 0x52 */ &NOP,
    /* 0x53 */ &NOP,
    /* 0x54 */ &NOP,
    /* 0x55 */ &NOP,
    /* 0x56 */ &NOP,
    /* 0x57 */ &NOP,
    /* 0x58 */ &NOP,
    /* 0x59 */ &NOP,
    /* 0x5a */ &NOP,
    /* 0x5b */ &NOP,
    /* 0x5c */ &NOP,
    /* 0x5d */ &NOP,
    /* 0x5e */ &NOP,
    /* 0x5f */ &NOP,
    /* 0x60 */ &NOP,
    /* 0x61 */ &NOP,
    /* 0x62 */ &NOP,
    /* 0x63 */ &NOP,
    /* 0x64 */ &NOP,
    /* 0x65 */ &NOP,
    /* 0x66 */ &NOP,
    /* 0x67 */ &NOP,
    /* 0x68 */ &NOP,
    /* 0x69 */ &NOP,
    /* 0x6a */ &NOP,
    /* 0x6b */ &NOP,
    /* 0x6c */ &NOP,
    /* 0x6d */ &NOP,
    /* 0x6e */ &NOP,
    /* 0x6f */ &NOP,
    /* 0x70 */ &NOP,
    /* 0x71 */ &NOP,
    /* 0x72 */ &NOP,
    /* 0x73 */ &NOP,
    /* 0x74 */ &NOP,
    /* 0x75 */ &NOP,
    /* 0x76 */ &NOP,
    /* 0x77 */ &NOP,
    /* 0x78 */ &NOP,
    /* 0x79 */ &NOP,
    /* 0x7a */ &NOP,
    /* 0x7b */ &NOP,
    /* 0x7c */ &NOP,
    /* 0x7d */ &NOP,
    /* 0x7e */ &NOP,
    /* 0x7f */ &NOP,
    /* 0x80 */ &NOP,
    /* 0x81 */ &NOP,
    /* 0x82 */ &NOP,
    /* 0x83 */ &NOP,
    /* 0x84 */ &NOP,
    /* 0x85 */ &NOP,
    /* 0x86 */ &NOP,
    /* 0x87 */ &NOP,
    /* 0x88 */ &NOP,
    /* 0x89 */ &NOP,
    /* 0x8a */ &NOP,
    /* 0x8b */ &NOP,
    /* 0x8c */ &NOP,
    /* 0x8d */ &NOP,
    /* 0x8e */ &NOP,
    /* 0x8f */ &NOP,
    /* 0x90 */ &NOP,
    /* 0x91 */ &NOP,
    /* 0x92 */ &NOP,
    /* 0x93 */ &NOP,
    /* 0x94 */ &NOP,
    /* 0x95 */ &NOP,
    /* 0x96 */ &NOP,
    /* 0x97 */ &NOP,
    /* 0x98 */ &NOP,
    /* 0x99 */ &NOP,
    /* 0x9a */ &NOP,
    /* 0x9b */ &NOP,
    /* 0x9c */ &NOP,
    /* 0x9d */ &NOP,
    /* 0x9e */ &NOP,
    /* 0x9f */ &NOP,
    /* 0xa0 */ &NOP,
    /* 0xa1 */ &NOP,
    /* 0xa2 */ &NOP,
    /* 0xa3 */ &NOP,
    /* 0xa4 */ &NOP,
    /* 0xa5 */ &NOP,
    /* 0xa6 */ &NOP,
    /* 0xa7 */ &NOP,
    /* 0xa8 */ &ExclusiveOr { reg: Reg8::B },
    /* 0xa9 */ &ExclusiveOr { reg: Reg8::C },
    /* 0xaa */ &ExclusiveOr { reg: Reg8::D },
    /* 0xab */ &ExclusiveOr { reg: Reg8::E },
    /* 0xac */ &ExclusiveOr { reg: Reg8::H },
    /* 0xad */ &ExclusiveOr { reg: Reg8::L },
    /* 0xae */ &NOP,
    /* 0xaf */ &ExclusiveOr { reg: Reg8::A },
    /* 0xb0 */ &NOP,
    /* 0xb1 */ &NOP,
    /* 0xb2 */ &NOP,
    /* 0xb3 */ &NOP,
    /* 0xb4 */ &NOP,
    /* 0xb5 */ &NOP,
    /* 0xb6 */ &NOP,
    /* 0xb7 */ &NOP,
    /* 0xb8 */ &NOP,
    /* 0xb9 */ &NOP,
    /* 0xba */ &NOP,
    /* 0xbb */ &NOP,
    /* 0xbc */ &NOP,
    /* 0xbd */ &NOP,
    /* 0xbe */ &NOP,
    /* 0xbf */ &NOP,
    /* 0xc0 */ &NOP,
    /* 0xc1 */ &NOP,
    /* 0xc2 */ &JumpImmediate {
        condition: Some(Condition::NZ),
    },
    /* 0xc3 */ &JumpImmediate { condition: None },
    /* 0xc4 */ &NOP,
    /* 0xc5 */ &NOP,
    /* 0xc6 */ &NOP,
    /* 0xc7 */ &NOP,
    /* 0xc8 */ &NOP,
    /* 0xc9 */ &NOP,
    /* 0xca */ &JumpImmediate {
        condition: Some(Condition::Z),
    },
    /* 0xcb */ &NOP,
    /* 0xcc */ &NOP,
    /* 0xcd */ &NOP,
    /* 0xce */ &NOP,
    /* 0xcf */ &NOP,
    /* 0xd0 */ &NOP,
    /* 0xd1 */ &NOP,
    /* 0xd2 */ &JumpImmediate {
        condition: Some(Condition::NC),
    },
    /* 0xd3 */ &NOP,
    /* 0xd4 */ &NOP,
    /* 0xd5 */ &NOP,
    /* 0xd6 */ &NOP,
    /* 0xd7 */ &NOP,
    /* 0xd8 */ &NOP,
    /* 0xd9 */ &NOP,
    /* 0xda */ &JumpImmediate {
        condition: Some(Condition::C),
    },
    /* 0xdb */ &NOP,
    /* 0xdc */ &NOP,
    /* 0xdd */ &NOP,
    /* 0xde */ &NOP,
    /* 0xdf */ &NOP,
    /* 0xe0 */ &LoadHigh {
        direction: Direction::ToBus,
    },
    /* 0xe1 */ &NOP,
    /* 0xe2 */ &NOP,
    /* 0xe3 */ &NOP,
    /* 0xe4 */ &NOP,
    /* 0xe5 */ &NOP,
    /* 0xe6 */ &NOP,
    /* 0xe7 */ &NOP,
    /* 0xe8 */ &NOP,
    /* 0xe9 */ &NOP,
    /* 0xea */ &NOP,
    /* 0xeb */ &NOP,
    /* 0xec */ &NOP,
    /* 0xed */ &NOP,
    /* 0xee */ &NOP,
    /* 0xef */ &NOP,
    /* 0xf0 */ &LoadHigh {
        direction: Direction::ToRegister,
    },
    /* 0xf1 */ &NOP,
    /* 0xf2 */ &NOP,
    /* 0xf3 */ &DisableInterrupts,
    /* 0xf4 */ &NOP,
    /* 0xf5 */ &NOP,
    /* 0xf6 */ &NOP,
    /* 0xf7 */ &NOP,
    /* 0xf8 */ &NOP,
    /* 0xf9 */ &NOP,
    /* 0xfa */ &NOP,
    /* 0xfb */ &NOP,
    /* 0xfc */ &NOP,
    /* 0xfd */ &NOP,
    /* 0xfe */ &CompareImmediate,
    /* 0xff */ &NOP,
];
